site_name: python-app-2
site_description: 'Main documentation for the python-app-2'
repo_url: https://github.com/scortellino/python-app-2
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'